version: '3.9'



services:

  GuiApp:
    command: uvicorn guiapp:app --host 0.0.0.0 --port 8000 --workers 1
    container_name: airifm
    build: 
      dockerfile: ./AiriApp/Dockerfile
      context: ./
    image: airifm
    volumes:
      - ./Data:/app/Data 
    ports:
      - 7534:8000

  GuiClient:
    build:
      context: ./GuiFrontend
      dockerfile: ./Dockerfile.dev
    image: guiclient.dev
    container_name: guiclient.dev
    environment:
      - VITE_GUI_BACKEND=http://195.209.214.211:7534
    ports:
    ports:
      - 3080:3000'
    volumes:
      - ./GuiFrontend:/app
      - /app/node_modules


