version: '3.9'


services:


  GuiClient:
    build:
      context: ./GuiFrontend
      dockerfile: ./Dockerfile.dev
    image: guiclient.dev
    container_name: guiclient.dev
    environment:
      - VITE_GUI_BACKEND=http://screener.airi.net:7534
      - MODE=development
    ports:
      - '3080:3000'
    volumes:
      - ./GuiFrontend:/app
      - /app/node_modules
    stdin_open: true


   
      
