# under this path all experiments' logs are saved
exp_dir: /home/jovyan/misha/experiments/screener

# path to the output directory, created dynamically by hydra
# path generation pattern is specified in `configs/hydra/default.yaml`
# use it to store all files generated during a particular run, like ckpts and metrics
output_dir: ${hydra:runtime.output_dir}

# path to the working directory
work_dir: ${hydra:runtime.cwd}